vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /upload/images
            upload_destination: '%kernel.project_dir%/public/upload/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
