<?php

namespace Container3UeHJhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A_UumVlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A.uumVl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A.uumVl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepo' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'image' => ['privates', '.errored..service_locator.A.uumVl.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.A.uumVl": it references class "App\\Entity\\Images" but no such service exists.'],
        ], [
            'commentRepo' => 'App\\Repository\\CommentRepository',
            'em' => '?',
            'image' => 'App\\Entity\\Images',
        ]);
    }
}
