<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAV9Vf0X\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAV9Vf0X/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAV9Vf0X.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAV9Vf0X\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAV9Vf0X\App_KernelProdContainer([
    'container.build_hash' => 'AV9Vf0X',
    'container.build_id' => '68a68e84',
    'container.build_time' => 1643381297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAV9Vf0X');
