<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'account' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/compte']], [], [], []],
    'account_password' => [[], ['_controller' => 'App\\Controller\\AccountPasswordController::index'], [], [['text', '/compte/modifier_motdepasse']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'home_image_show' => [['id'], ['_controller' => 'App\\Controller\\HomeController::show'], ['id' => '[0-9]+'], [['variable', '/', '[0-9]+', 'id', true], ['text', '/image']], [], [], []],
    'create_image' => [[], ['_controller' => 'App\\Controller\\ImageController::index'], [], [['text', '/nouvelle/image']], [], [], []],
    'edit_image' => [['id'], ['_controller' => 'App\\Controller\\ImageController::edit'], ['id' => '[0-9]+'], [['text', '/modifier'], ['variable', '/', '[0-9]+', 'id', true], ['text', '/image']], [], [], []],
    'delete_image' => [['id'], ['_controller' => 'App\\Controller\\ImageController::delete'], ['id' => '[0-9]+'], [['text', '/supprimer'], ['variable', '/', '[0-9]+', 'id', true], ['text', '/image']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/inscription']], [], [], []],
    'confirm_account' => [['token'], ['_controller' => 'App\\Controller\\RegisterController::confirmAccount'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/confirmer']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], [], []],
    'liip_imagine_filter_runtime' => [['filter', 'hash', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterRuntimeAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[^/]++', 'hash', true], ['text', '/rc'], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], [], []],
    'liip_imagine_filter' => [['filter', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], [], []],
];
