<?php

namespace ContainerT9fBsd6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VTIPEJdService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.vTIPEJd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vTIPEJd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'image' => ['privates', '.errored..service_locator.vTIPEJd.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.vTIPEJd": it references class "App\\Entity\\Images" but no such service exists.'],
            'token' => ['services', '.container.private.security.token_storage', 'get_Container_Private_Security_TokenStorageService', false],
        ], [
            'em' => '?',
            'image' => 'App\\Entity\\Images',
            'token' => '?',
        ]);
    }
}
