<?php

namespace ContainerT9fBsd6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BL8pHVqService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.BL8pHVq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BL8pHVq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imagesRepo' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService', true],
        ], [
            'imagesRepo' => 'App\\Repository\\ImagesRepository',
        ]);
    }
}
