<?php

namespace ContainerT9fBsd6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImages2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vTIPEJd.App\Entity\Images' shared service.
     *
     * @return \App\Entity\Images
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vTIPEJd": it references class "App\\Entity\\Images" but no such service exists.');
    }
}
