<?php

namespace ContainerAV9Vf0X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_ImagickService extends App_KernelProdContainer
{
    /*
     * Gets the private 'liip_imagine.imagick' shared service.
     *
     * @return \Imagine\Imagick\Imagine
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['liip_imagine.imagick'] = $instance = new \Imagine\Imagick\Imagine();

        $instance->setMetadataReader(new \Imagine\Image\Metadata\DefaultMetadataReader());

        return $instance;
    }
}
