<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBy9Mm7O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBy9Mm7O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBy9Mm7O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBy9Mm7O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBy9Mm7O\App_KernelDevDebugContainer([
    'container.build_hash' => 'By9Mm7O',
    'container.build_id' => 'f166b28a',
    'container.build_time' => 1643993585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBy9Mm7O');
