<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCLjOQho\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCLjOQho/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCLjOQho.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCLjOQho\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCLjOQho\App_KernelDevDebugContainer([
    'container.build_hash' => 'CLjOQho',
    'container.build_id' => '285087e1',
    'container.build_time' => 1644159271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCLjOQho');
